# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reply', models.BooleanField(default=True, verbose_name='是否上课')),
                ('not_reply_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='翘课原因')),
                ('state', models.TextField(verbose_name='上课状态')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '试听记录',
                'verbose_name_plural': '试听记录',
            },
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reply', models.BooleanField(default=True, verbose_name='是否回复')),
                ('not_reply_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='未回复原因')),
                ('way', models.IntegerField(choices=[(0, 'QQ'), (1, '电话'), (2, '微信')], null=True, verbose_name='咨询方式')),
                ('grade', models.CharField(blank=True, max_length=255, null=True, verbose_name='所属等级')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '咨询记录',
                'verbose_name_plural': '咨询记录',
            },
        ),
        migrations.CreateModel(
            name='ConsultTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '咨询标签',
                'verbose_name_plural': '咨询标签',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='姓名')),
                ('tel', models.CharField(max_length=20, null=True, verbose_name='手机号码')),
                ('category', models.IntegerField(choices=[(0, '父亲'), (1, '母亲'), (2, '爷爷'), (3, '奶奶'), (4, '外公'), (5, '外婆')], null=True, verbose_name='关系类型')),
            ],
            options={
                'verbose_name': '准学员联系人',
                'verbose_name_plural': '准学员联系人',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reply', models.BooleanField(default=True, verbose_name='是否回复')),
                ('not_reply_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='未回复原因')),
                ('invitation_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='邀请时间')),
                ('agree_invitation', models.BooleanField(default=True, verbose_name='是否应邀')),
                ('agree_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='应邀时间')),
                ('interview_contents', models.TextField(blank=True, verbose_name='面谈内容')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邀约',
                'verbose_name_plural': '邀约',
            },
        ),
        migrations.CreateModel(
            name='PreStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_following', models.BooleanField(default=False, verbose_name='跟进中')),
            ],
            options={
                'verbose_name': '准学员',
                'verbose_name_plural': '准学员',
            },
        ),
        migrations.CreateModel(
            name='PreStudentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '准学员所属分类',
                'verbose_name_plural': '准学员所属分类',
            },
        ),
        migrations.CreateModel(
            name='PreStudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '准学员所属年级',
                'verbose_name_plural': '准学员所属年级',
            },
        ),
        migrations.CreateModel(
            name='PreStudentSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '准学员所属学校',
                'verbose_name_plural': '准学员所属学校',
            },
        ),
        migrations.CreateModel(
            name='PreStudentSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '准学员来源',
                'verbose_name_plural': '准学员来源',
            },
        ),
        migrations.CreateModel(
            name='RecommendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_tel', models.CharField(max_length=20, null=True, verbose_name='推荐人号码')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='推荐时间')),
                ('is_rebate', models.BooleanField(default=True, verbose_name='是否继续返利')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '推荐记录',
                'verbose_name_plural': '推荐记录',
            },
        ),
    ]
