# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('admission', '0001_initial'),
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendrecord',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommend_record_to_user', to=settings.AUTH_USER_MODEL, verbose_name='被推荐人'),
        ),
        migrations.AddField(
            model_name='prestudentsource',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_source_branch', to='school.Branch', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='prestudentschool',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_school_branch', to='school.Branch', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='prestudentclass',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_class_branch', to='school.Branch', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='prestudentcategory',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_category_branch', to='school.Branch', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='prestudent',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_branch', to='school.Branch', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='prestudent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consult_category', to='admission.PreStudentCategory', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='prestudent',
            name='courses',
            field=models.ManyToManyField(blank=True, to='education.Course', verbose_name='意向课程'),
        ),
        migrations.AddField(
            model_name='prestudent',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_follower', to=settings.AUTH_USER_MODEL, verbose_name='当前跟进人'),
        ),
        migrations.AddField(
            model_name='prestudent',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_source', to='admission.PreStudentSource', verbose_name='来源渠道'),
        ),
        migrations.AddField(
            model_name='prestudent',
            name='source_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_source_class', to='admission.PreStudentClass', verbose_name='所属年级'),
        ),
        migrations.AddField(
            model_name='prestudent',
            name='source_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_source_school', to='admission.PreStudentSchool', verbose_name='来源学校'),
        ),
        migrations.AddField(
            model_name='prestudent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='对应用户'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_branch', to='school.Branch', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_follower', to=settings.AUTH_USER_MODEL, verbose_name='邀约人'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='pre_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_pre_student', to='admission.PreStudent', verbose_name='准学员'),
        ),
        migrations.AddField(
            model_name='consulttag',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consult_tag_branch', to='school.Branch', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='consult',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consult_branch', to='school.Branch', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='consult',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='admission.Contact', verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='consult',
            name='courses',
            field=models.ManyToManyField(blank=True, to='education.Course', verbose_name='意向课程'),
        ),
        migrations.AddField(
            model_name='consult',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consult_event', to='market.DiscountEvent', verbose_name='市场活动'),
        ),
        migrations.AddField(
            model_name='consult',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consult_follower', to=settings.AUTH_USER_MODEL, verbose_name='咨询人'),
        ),
        migrations.AddField(
            model_name='consult',
            name='marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consult_marketer', to=settings.AUTH_USER_MODEL, verbose_name='市场人员'),
        ),
        migrations.AddField(
            model_name='consult',
            name='pre_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consult_pre_student', to='admission.PreStudent', verbose_name='准学员'),
        ),
        migrations.AddField(
            model_name='consult',
            name='tags',
            field=models.ManyToManyField(blank=True, to='admission.ConsultTag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='auditionrecord',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audition_record_branch', to='school.Branch', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='auditionrecord',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audition_course', to='education.Course', verbose_name='试听课程'),
        ),
        migrations.AddField(
            model_name='auditionrecord',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audition_record_follower', to=settings.AUTH_USER_MODEL, verbose_name='试听安排人'),
        ),
        migrations.AddField(
            model_name='auditionrecord',
            name='pre_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audition_record_pre_student', to='admission.PreStudent', verbose_name='准学员'),
        ),
    ]
