# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0003_auto_20170329_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'permissions': (('view_emailtemplate', 'Can view 邮件模板'),), 'verbose_name': '邮件模板', 'verbose_name_plural': '邮件模板'},
        ),
    ]
