# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0004_auto_20170330_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'permissions': (('view_email', 'Can view 邮件'),), 'verbose_name': '邮件', 'verbose_name_plural': '邮件'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': (('view_notification', 'Can view 通知'),), 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'permissions': (('view_notificationtemplate', 'Can view 通知模板'),), 'verbose_name': '通知模板', 'verbose_name_plural': '通知模板'},
        ),
        migrations.AlterModelOptions(
            name='workreport',
            options={'permissions': (('view_workreport', 'Can view 工作报告'),), 'verbose_name': '工作报告', 'verbose_name_plural': '工作报告'},
        ),
        migrations.AlterModelOptions(
            name='workreporttemplate',
            options={'permissions': (('view_workreporttemplate', 'Can view 工作报告模板'),), 'verbose_name': '工作报告模板', 'verbose_name_plural': '工作报告模板'},
        ),
    ]
