# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='账户余额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '余额',
                'verbose_name_plural': '余额',
            },
        ),
        migrations.CreateModel(
            name='BalanceChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='变更金额')),
                ('value_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='变更后余额')),
                ('change_reason', models.CharField(max_length=255, null=True, verbose_name='变更原因')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '余额变更记录',
                'verbose_name_plural': '余额变更记录',
            },
        ),
        migrations.CreateModel(
            name='BalanceReChargeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(max_length=255, null=True, verbose_name='商户订单编号')),
                ('platform', models.IntegerField(choices=[(0, '支付宝'), (1, '微信')], null=True, verbose_name='支付平台')),
                ('trade_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='支付平台编号')),
                ('recharge_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='充值金额')),
                ('recharge_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='实际到账金额')),
                ('is_pay', models.BooleanField(default=False, verbose_name='是否付款')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('timeout_express', models.CharField(max_length=10, null=True, verbose_name='超时时间')),
                ('is_abandon', models.BooleanField(default=False, verbose_name='是否作废')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '余额充值记录',
                'verbose_name_plural': '余额充值记录',
            },
        ),
        migrations.CreateModel(
            name='IncomeExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_expense', models.IntegerField(choices=[(0, '收入'), (1, '支出')], null=True, verbose_name='收入/支出')),
                ('category', models.IntegerField(choices=[(0, '购课'), (1, '充值'), (2, '其他入账'), (3, '工资'), (4, '提成'), (5, '其他出账')], null=True, verbose_name='收支类型')),
                ('reason', models.TextField(verbose_name='收支款原因')),
                ('approval_result', models.IntegerField(choices=[(0, '待审批'), (1, '审批通过'), (2, '审批拒绝')], null=True, verbose_name='审批结果')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='经办金额')),
                ('is_receive_pay', models.BooleanField(default=False, verbose_name='是否收支款')),
                ('receive_pay_way', models.CharField(max_length=255, null=True, verbose_name='收支款方式')),
                ('trade_no', models.CharField(max_length=255, null=True, verbose_name='收支款流水号')),
                ('receive_pay_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='收支款时间')),
                ('note', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('is_abandon', models.BooleanField(default=False, verbose_name='是否作废')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '收支款项',
                'verbose_name_plural': '收支款项',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='积分值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '积分',
                'verbose_name_plural': '积分',
            },
        ),
        migrations.CreateModel(
            name='PointChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_value', models.IntegerField(default=0, verbose_name='变更积分值')),
                ('value_after', models.IntegerField(default=0, verbose_name='变更后积分值')),
                ('change_reason', models.CharField(max_length=255, null=True, verbose_name='变更原因')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '积分变更记录',
                'verbose_name_plural': '积分变更记录',
            },
        ),
        migrations.CreateModel(
            name='PointReChargeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(max_length=255, null=True, verbose_name='商户订单编号')),
                ('platform', models.IntegerField(choices=[(0, '支付宝'), (1, '微信')], null=True, verbose_name='支付平台')),
                ('trade_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='支付平台编号')),
                ('recharge_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='充值金额')),
                ('recharge_point', models.IntegerField(default=0, verbose_name='充值积分')),
                ('is_pay', models.BooleanField(default=False, verbose_name='是否付款')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('timeout_express', models.CharField(max_length=10, null=True, verbose_name='超时时间')),
                ('is_abandon', models.BooleanField(default=False, verbose_name='是否作废')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '积分充值记录',
                'verbose_name_plural': '积分充值记录',
            },
        ),
        migrations.CreateModel(
            name='PreStudentPaymentDeduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.IntegerField(choices=[(0, '介绍'), (1, '推荐人'), (2, '主动咨询'), (3, '邀约'), (4, '安排试听'), (5, '试听讲师'), (6, '其他')], null=True, verbose_name='提成原因')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总提成金额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='修正金额')),
                ('real_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='实际提成金额')),
                ('is_abandon', models.BooleanField(default=False, verbose_name='是否作废')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '购课提成',
                'verbose_name_plural': '购课提成',
            },
        ),
        migrations.CreateModel(
            name='PreStudentPaymentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总金额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='折扣金额')),
                ('real_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='实际支付金额')),
                ('is_abandon', models.BooleanField(default=False, verbose_name='是否作废')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '购课子记录',
                'verbose_name_plural': '购课子记录',
            },
        ),
        migrations.CreateModel(
            name='PreStudentPaymentRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总金额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='折扣金额')),
                ('real_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='实际支付金额')),
                ('is_abandon', models.BooleanField(default=False, verbose_name='是否作废')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('courses', models.ManyToManyField(blank=True, to='education.Course', verbose_name='报名课程')),
            ],
            options={
                'verbose_name': '购课记录',
                'verbose_name_plural': '购课记录',
            },
        ),
    ]
