# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestudentpaymentrecords',
            name='discount_coupon_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_payment_records_discount_coupon_record', to='market.DiscountCouponRecord', verbose_name='优惠券领取记录'),
        ),
        migrations.AddField(
            model_name='prestudentpaymentrecords',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_payment_records_event', to='market.DiscountEvent', verbose_name='市场活动'),
        ),
        migrations.AddField(
            model_name='prestudentpaymentrecords',
            name='income_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_payment_records_income_expense', to='finance.IncomeExpense', verbose_name='收支记录'),
        ),
        migrations.AddField(
            model_name='prestudentpaymentrecords',
            name='items',
            field=models.ManyToManyField(blank=True, to='finance.PreStudentPaymentItem', verbose_name='子订单支付记录'),
        ),
    ]
