# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_auto_20170329_1801'),
        ('education', '0002_auto_20170329_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestudentpaymentrecords',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_payment_records_user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='prestudentpaymentitem',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_payment_item_course', to='education.Course', verbose_name='课程名称'),
        ),
        migrations.AddField(
            model_name='prestudentpaymentitem',
            name='income_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_payment_item_income_expense', to='finance.IncomeExpense', verbose_name='收支记录'),
        ),
        migrations.AddField(
            model_name='prestudentpaymentitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_payment_item_user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='prestudentpaymentdeduct',
            name='income_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_payment_deduct_income_expense', to='finance.IncomeExpense', verbose_name='收支记录'),
        ),
        migrations.AddField(
            model_name='prestudentpaymentdeduct',
            name='payment_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_payment_deduct_payment_item', to='finance.PreStudentPaymentItem', verbose_name='购课记录'),
        ),
        migrations.AddField(
            model_name='prestudentpaymentdeduct',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_student_payment_deduct_user', to=settings.AUTH_USER_MODEL, verbose_name='提成人'),
        ),
        migrations.AddField(
            model_name='pointrechargelog',
            name='income_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_recharge_log_income_expense', to='finance.IncomeExpense', verbose_name='收支记录'),
        ),
        migrations.AddField(
            model_name='pointrechargelog',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_recharge_log_point', to='finance.Point', verbose_name='积分充值订单'),
        ),
        migrations.AddField(
            model_name='pointchangelog',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_change_log_point', to='finance.Point', verbose_name='积分'),
        ),
        migrations.AddField(
            model_name='point',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='incomeexpense',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_expense_agent', to=settings.AUTH_USER_MODEL, verbose_name='经办人'),
        ),
        migrations.AddField(
            model_name='incomeexpense',
            name='approval_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_expense_approval_user', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='balancerechargelog',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_recharge_log_balance', to='finance.Balance', verbose_name='余额'),
        ),
        migrations.AddField(
            model_name='balancerechargelog',
            name='discount_coupon_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_recharge_log_discount_coupon_record', to='market.DiscountCouponRecord', verbose_name='对应优惠券'),
        ),
        migrations.AddField(
            model_name='balancerechargelog',
            name='discount_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_recharge_log_discount_event', to='market.DiscountEvent', verbose_name='优惠活动'),
        ),
        migrations.AddField(
            model_name='balancerechargelog',
            name='income_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_recharge_log_income_expense', to='finance.IncomeExpense', verbose_name='收支记录'),
        ),
        migrations.AddField(
            model_name='balancechangelog',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_change_log_balance', to='finance.Balance', verbose_name='余额'),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
