# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 03:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_auto_20170329_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_expense', models.IntegerField(choices=[(0, '收入'), (1, '支出')], null=True, verbose_name='收入/支出')),
                ('category', models.IntegerField(choices=[(0, '购课'), (1, '充值'), (2, '其他入账'), (3, '工资'), (4, '提成'), (5, '其他出账')], null=True, verbose_name='收支类型')),
                ('reason', models.TextField(verbose_name='收支款原因')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='经办金额')),
                ('is_receive_pay', models.BooleanField(default=False, verbose_name='是否收支款')),
                ('receive_pay_way', models.CharField(max_length=255, null=True, verbose_name='收支款方式')),
                ('trade_no', models.CharField(max_length=255, null=True, verbose_name='收支款流水号')),
                ('receive_pay_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='收支款时间')),
                ('note', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('is_abandon', models.BooleanField(default=False, verbose_name='是否作废')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_expense_item_user', to=settings.AUTH_USER_MODEL, verbose_name='打/收款人')),
            ],
            options={
                'verbose_name_plural': '收支子款项',
                'verbose_name': '收支子款项',
            },
        ),
        migrations.AddField(
            model_name='incomeexpense',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_expense_user', to=settings.AUTH_USER_MODEL, verbose_name='打/收款人'),
        ),
        migrations.AddField(
            model_name='incomeexpense',
            name='items',
            field=models.ManyToManyField(to='finance.IncomeExpenseItem', verbose_name='子收支款项'),
        ),
    ]
