# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('list_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '校区',
                'verbose_name_plural': '校区',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('list_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('list_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, choices=[(0, '教学人员'), (1, '招生人员'), (2, '管理人员'), (3, '其他')], null=True, verbose_name='员工类型')),
                ('id_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证')),
                ('bank_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='银行卡号码')),
                ('social_security_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='社保号')),
                ('on_job', models.BooleanField(default=True, verbose_name='是否在职')),
                ('job_state', models.IntegerField(blank=True, choices=[(0, '全职'), (1, '兼职')], null=True, verbose_name='入职类型')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_branch', to='school.Branch', verbose_name='校区')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
        ),
    ]
