# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='对应用户'),
        ),
        migrations.AddField(
            model_name='school',
            name='branches',
            field=models.ManyToManyField(blank=True, to='school.Branch', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='school',
            name='departments',
            field=models.ManyToManyField(blank=True, to='school.Department', verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='department',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='_department_departments_+', to='school.Department', verbose_name='子部门'),
        ),
        migrations.AddField(
            model_name='department',
            name='staffs',
            field=models.ManyToManyField(blank=True, to='school.Staff', verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='branch',
            name='departments',
            field=models.ManyToManyField(blank=True, to='school.Department', verbose_name='部门'),
        ),
    ]
