# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20170330_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'permissions': (('view_branch', 'Can view 校区'),), 'verbose_name': '校区', 'verbose_name_plural': '校区'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': (('view_department', 'Can view 部门'),), 'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': (('view_staff', 'Can view 员工'),), 'verbose_name': '员工', 'verbose_name_plural': '员工'},
        ),
    ]
