# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0002_auto_20170329_1801'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsrecord',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_record_from_user', to=settings.AUTH_USER_MODEL, verbose_name='发送人'),
        ),
        migrations.AddField(
            model_name='smsassign',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_assign_branch', to='school.Branch', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='smsassign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_assign_user', to=settings.AUTH_USER_MODEL, verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='sms',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_branch', to='school.Branch', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='sms',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_from_user', to=settings.AUTH_USER_MODEL, verbose_name='撰写人'),
        ),
        migrations.AddField(
            model_name='noticetemplate',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_template_branch', to='school.Branch', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='notice',
            name='branches',
            field=models.ManyToManyField(blank=True, to='school.Branch', verbose_name='所属校区'),
        ),
        migrations.AddField(
            model_name='notice',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_from_user', to=settings.AUTH_USER_MODEL, verbose_name='撰写人'),
        ),
    ]
