# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': '该号码已被注册'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('portrait', models.ImageField(blank=True, default='default.png', storage=user.storage.ImageStorage(base_url='/media/user/', location='C:\\django\\SchoolMS\\media/user/'), upload_to='', verbose_name='头像')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '女'), (1, '男'), (2, '保密')], null=True, verbose_name='性别')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='姓名')),
                ('birth_day', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='生日')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='电子邮件')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码')),
                ('fixed_tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='固定电话')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ')),
                ('we_chat', models.CharField(blank=True, max_length=40, null=True, verbose_name='微信')),
                ('contact_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系地址')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('branches', models.ManyToManyField(blank=True, to='school.Branch', verbose_name='校区')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'permissions': (('view_user', 'Can view 用户'),),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default='', max_length=40, verbose_name='授权Token')),
                ('refresh_token', models.CharField(default='', max_length=40, verbose_name='刷新Token')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='对应用户')),
            ],
            options={
                'verbose_name': '令牌',
                'verbose_name_plural': '令牌',
            },
        ),
    ]
