# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='content',
            field=models.TextField(verbose_name='日志内容'),
        ),
    ]
